name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.0
      with:
        switches: -avzr --delete --exclude=".env,public/images"
        remote_path: ~/app/microsite-logos-backend
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.PRIVATE_KEY }}
    - name: executing remote ssh commands using PRIVATE_KEY
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/app/microsite-logos-backend
          npm i
          source ~/.profile
          pm2 stop microsite-backend
          npm run start:dev
