name: CI

on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      USER_ROOT: ${{ secrets.USER_ROOT }}
      PASS: ${{ secrets.PASS }}
      ROLE: ${{ secrets.ROLE }}
      ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
      REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
      JWT_ACC_TOKEN_EXP: ${{ secrets.JWT_ACC_TOKEN_EXP }}
      JWT_REF_TOKEN_EXP: ${{ secrets.JWT_REF_TOKEN_EXP }}
      NAME_DB_DEV: ${{ secrets.NAME_DB_DEV }}
      HOST_DB: ${{ secrets.HOST_DB }}
      PASS_DB: ${{ secrets.PASS_DB }}
      USER_DB: ${{ secrets.USER_DB }}
      PORT_DB: ${{ secrets.PORT_DB}}
    steps:
    - uses: actions/checkout@v2
    - name: Starting test
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present
    - run: npm test
